# Site settings
title: Das-Projekt-Zğ›¼
email: hu_wong@126.com
description: > # this means to ignore newlines until "baseurl:"
  <h2> æ”¯å­¸å¯¶ | æ¥­å‹™é€šè¨Š <br /></h2>
  â€œDo small things with great love.â€
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: huWONGplus
github_username:  DasProjektZ

# Build settings
markdown: kramdown
